# Put the path to your vault here
VAULT_PATH = "path/to/your/vault"

# WHAT DO YOU WANT?!?!?
BASIC_FORMATTING = True
DEFINITION_FORMATTING = True
WIKILINKS_FORMATTING = True

# PROVIDE YOUR TITLES AND HEADERS TO THE MODEL?
# THIS IMPROVES WIKILINKS FORMATTING - RECOMMENDED HIGHLY
TITLES_AND_HEADERS = True

# DO NOT CHANGE THIS
SETTINGS = {
    "BASIC_FORMATTING": BASIC_FORMATTING,
    "DEFINITION_FORMATTING": DEFINITION_FORMATTING,
    "WIKILINKS_FORMATTING": WIKILINKS_FORMATTING,
}